import { StudyLesson } from "./studyLesson";

// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Response {
  operationSuccessful: boolean;
  data:                Data;
}

export interface Data {
  studyLessons:             StudyLesson[];
  lessonBlogMap:            LessonBlogMap;
  firstLesson:              boolean;
  accountabilityConfigured: boolean;
}

export interface LessonBlogMap {
}
